### ISSUE TITLE
URL redirection forbidden

### ISSUE THREAD

**Issue by thomaswelton** [cnorthwood/eurovisionhue#4]
Getting this when running the program

.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/open-uri.rb:223:in `open_loop': redirection forbidden: http://www.eurovision.tv/live/live_story_the_grand_final -> https://eurovision.tv/live/live_story_the_grand_final (RuntimeError)
	from /Users/carolineinnes/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/open-uri.rb:149:in `open_uri'
	from /Users/carolineinnes/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/open-uri.rb:703:in `open'
	from /Users/carolineinnes/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/open-uri.rb:34:in `open'
	from eurovisionhue.rb:55:in `<main>'

**Comment by cnorthwood** [comment]
I suspect that the URLs have changed from last year, I'll be having a go at making it work for this year shortly
